name: Latest Medium Story Workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest Medium post
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kalibetre/kalibetre@main
        with:
          comment_tag_name: "MEDIUM-STORY-LIST"
          feed_list: "https://medium.com/feed/@kalibetre"
